disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - type_body_length
  - type_name
opt_in_rules:
  - empty_count
  - for_where
  - nimble_operator
  - quick_discouraged_focused_test
  - single_test_class
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
